print("Enter Student Name")
name=input()
print("Enter Mark1:")
mark1=input()
print("Enterr Mark2:")
mark2=input()
print("Enter Mark3:")
mark3=input()
print("Enter Mark4:")
mark4=input()
print("Enter Mark5:")
mark5=input()
total=(int(mark1)+int(mark2)+int(mark3)+int(mark4)+int(mark5))
print("Total Marks is" ,total )
print("Average mark of student1 is", (total/5))

